export default {
    bucketPrefix: 'https://dalma-daniela.s3.us-east-2.amazonaws.com/assets/',
    folders: {
        dalma: {
            dalmaInstagramPhone: 'dalma/dalmaInstagramPhone.png',
            dalmaLanding: 'dalma/dalmaLanding.png',
            dalmaLinkedInLaptop: 'dalma/dalmaLinkedInLaptop.png',
            dalmaiVisa: 'dalma/dalmaiVisa.png',
        },
        films: {
            limeAndVinegar: 'films/limeAndVinegar.png',
            theSovereign: 'films/theSovereign.png',
        },
        icons: {
            email: 'icons/email.svg',
            facebook: 'icons/facebook.svg',
            instagram: 'icons/instagram.svg',
            linkedIn: 'icons/linkedIn.svg',
            shareNeon: 'icons/shareNeon.webp',
            syringe: 'icons/syringe.png',
            threads: 'icons/threads.svg',
        },
        logos: {
            bioOptimizers: 'logos/bioOptimizers.png',
            celebMix: 'logos/celebMix.png',
            dominant: 'logos/dominant.png',
            eoApp: 'logos/eoApp.png',
            errante: 'logos/errante.png',
            flanelle: 'logos/flanelle.png',
            fridays: 'logos/fridays.png',
            hardRockCafe: 'logos/hardRockCafe.png',
            iVisa: 'logos/iVisa.png',
            index: 'logos/index.js',
            it49: 'logos/it49.png',
            laWeekly: 'logos/laWeekly.png',
            lilyJade: 'logos/lilyJade.png',
            mamb: 'logos/mamb.png',
            nyWeekly: 'logos/nyWeekly.png',
            nyWire: 'logos/nyWire.png',
            sunMed: 'logos/sunMed.png',
            sunWink: 'logos/sunWink.png',
            uptime: 'logos/uptime.png',
            versed: 'logos/versed.png',
            vireo: 'logos/vireo.png',
        },
        magic: {
            magic1: 'magic/magic1.webp',
            magic2: 'magic/magic2.webp',
            magic3: 'magic/magic3.webp',
            magic4: 'magic/magic4.webp',
            magic5: 'magic/magic5.webp',
            magic6: 'magic/magic6.webp',
            magic7: 'magic/magic7.webp',
            magic8: 'magic/magic8.webp',
            magic9: 'magic/magic9.webp',
            magic10: 'magic/magic10.webp',
        },
        stars: {
            starDownwardSpiral: 'stars/starDownwardSpiral.webp',
            starSwirl: 'stars/starSwirl.webp',
            starTwinkleSmall: 'stars/starTwinkleSmall.webp',
            starTwinklesLarge: 'stars/starTwinklesLarge.webp',
        },
        stock: {
            bullseye: 'stock/bullseye.webp',
            consistency: 'stock/consistency.jpeg',
            jayShettyVideo: 'stock/jayShettyVideo.png',
            purpose: 'stock/purpose.webp',
            whiteChick: 'stock/whiteChick.png',
        },
        team: {
            cami: 'team/cami.jpeg',
            corey: 'team/corey.jpeg',
            dalma: 'team/dalma.jpeg',
            juancho: 'team/juancho.jpeg',
        },
        testimonials: {
            alexTestimonialPhone: 'testimonials/alexTestimonialPhone.png',
            camiTestimonialPhone: 'testimonials/camiTestimonialPhone.png',
            evanTestimonialPhone: 'testimonials/evanTestimonialPhone.png',
            garrettTestimonialPhone: 'testimonials/garrettTestimonialPhone.png',
        },
        videos: {
            plantGrowing: 'videos/plantGrowing.mov',
            tvStatic: 'videos/tvStatic.mp4',
        }
    }
}