export const INCREMENT_ENTHUSIASM = 'INCREMENT_ENTHUSIASM';
export type INCREMENT_ENTHUSIASM = typeof INCREMENT_ENTHUSIASM;

export const DECREMENT_ENTHUSIASM = 'DECREMENT_ENTHUSIASM';
export type DECREMENT_ENTHUSIASM = typeof DECREMENT_ENTHUSIASM;

export const CONNECT_ACCOUNT = 'CONNECT_ACCOUNT';
export type CONNECT_ACCOUNT = typeof CONNECT_ACCOUNT;

export const DISCONNECT_ACCOUNT = 'DISCONNECT_ACCOUNT';
export type DISCONNECT_ACCOUNT = typeof DISCONNECT_ACCOUNT;

export const UPDATE_TEXT_FIELD = 'UPDATE_TEXT_FIELD';
export type UPDATE_TEXT_FIELD = typeof UPDATE_TEXT_FIELD;

export const RESET_TEXT_FIELD = 'RESET_TEXT_FIELD';
export type RESET_TEXT_FIELD = typeof RESET_TEXT_FIELD;

export const SUBMIT_FORM = 'SUBMIT_FORM';
export type SUBMIT_FORM = typeof SUBMIT_FORM;
